/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify Grouping of Passing and Failing Test Suites
 * Ticket: testable#273 · Case: b858857c-4add-4755-8245-cef25db56456 · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("testable#273 Verify Grouping of Passing and Failing Test Suites @case:b858857c-4add-4755-8245-cef25db56456", async ({ page }) => {
  // 1. Navigate and confirm redirect to /auth/login
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForTimeout(2000);
  await shot(page, "initial-load");

  await expect(page).toHaveURL("http://localhost:3000/auth/login");

  // 2 & 3. Verify demo panel shows PASS grouping for auth/login.test.ts with its checks
  await expect(page.getByText("Ship with confidence.")).toBeVisible();
  await shot(page, "demo-panel-heading");

  await expect(page.getByText("PASS auth/login.test.ts")).toBeVisible();
  await shot(page, "pass-suite-grouping");

  await expect(page.getByText("validates credentials")).toBeVisible();
  await expect(page.getByText("rejects expired tokens")).toBeVisible();
  await expect(page.getByText("enforces rate limit")).toBeVisible();
  await shot(page, "passing-checks-listed");

  // 4. Fill credentials
  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");

  await emailInput.click();
  await emailInput.pressSequentially("testuser@example.com", { delay: 30 });
  await shot(page, "email-filled");

  await passwordInput.click();
  await passwordInput.pressSequentially("ValidPassword123!", { delay: 30 });
  await shot(page, "password-filled");

  // 5. Click Authenticate
  await page.getByRole("button", { name: "Authenticate" }).click();
  await page.waitForTimeout(3000);
  await shot(page, "after-authenticate");

  // Expected: since these credentials are fictitious (no real account exists),
  // the app correctly rejects the login attempt and keeps the user on the
  // /auth/login page with the login form still available.
  await expect(page).toHaveURL("http://localhost:3000/auth/login");
  await expect(page.getByRole("button", { name: "Authenticate" })).toBeVisible();
  await shot(page, "post-login-page");
});