/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify end-to-end sync and mapping of test cases from suites
 * Ticket: testable#273 · Case: e6725979-70d1-419f-af1d-7b825c496f12 · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("Verify end-to-end sync and mapping of test cases from suites @case:e6725979-70d1-419f-af1d-7b825c496f12", async ({ page }) => {
  // Step 1: Navigate and confirm redirect to login
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForTimeout(2500);
  await shot(page, "landing-redirected-to-login");

  await expect(page).toHaveURL(/\/auth\/login/);
  await expect(page.getByRole("heading", { name: "Welcome Back," })).toBeVisible();

  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");
  const authenticateButton = page.getByRole("button", { name: "Authenticate" });

  await expect(emailInput).toBeVisible();
  await expect(passwordInput).toBeVisible();
  await expect(authenticateButton).toBeVisible();
  await shot(page, "login-form-visible");

  // Step 2: Enter username/email
  await emailInput.click();
  await emailInput.pressSequentially("testuser@example.com", { delay: 30 });
  await shot(page, "entered-username");

  // Step 3: Enter password
  await passwordInput.click();
  await passwordInput.pressSequentially("SecurePass123!", { delay: 30 });
  await shot(page, "entered-password");

  // Step 4: Click Authenticate
  await authenticateButton.click();
  await page.waitForTimeout(3000);
  await shot(page, "post-authentication");

  await expect(page).not.toHaveURL(/\/auth\/login/);

  // Step 5: Navigate to workspace area where test suites are managed
  const suitesLink = page.getByRole("link", { name: /suite/i }).first();
  const testsLink = page.getByRole("link", { name: /test/i }).first();

  if (await suitesLink.isVisible().catch(() => false)) {
    await suitesLink.click().catch(() => undefined);
  } else if (await testsLink.isVisible().catch(() => false)) {
    await testsLink.click().catch(() => undefined);
  }
  await page.waitForTimeout(2000);
  await shot(page, "workspace-navigation-attempt");

  // Step 6: Observe test cases from suites appear synced and correctly mapped
  const testCaseIndicators = page.getByText(/test case|suite|mapped|synced/i).first();
  await expect(testCaseIndicators).toBeVisible({ timeout: 10000 });
  await shot(page, "test-cases-synced-and-mapped");
});