/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify Error Handling for Invalid PAT
 * Ticket: testable#273 · Case: a6a53390-9c56-4efc-b062-05536087a31e · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("testable#273 — Verify Error Handling for Invalid PAT @case:a6a53390-9c56-4efc-b062-05536087a31e", async ({ page }) => {
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForTimeout(2500);

  await shot(page, "login-page-loaded");

  const heading = page.getByRole("heading", { name: "Welcome Back," });
  await expect(heading).toBeVisible();

  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");

  await emailInput.click();
  await emailInput.pressSequentially("testuser@example.com", { delay: 30 });
  await shot(page, "filled-username");

  await passwordInput.click();
  await passwordInput.pressSequentially("invalid_pat_1234567890_malformed", { delay: 30 });
  await shot(page, "filled-invalid-pat");

  const authenticateButton = page.getByRole("button", { name: "Authenticate" });
  await authenticateButton.click();

  await page.waitForTimeout(2500);
  await shot(page, "after-authenticate-submit");

  // Expect to remain on the login page — no navigation to authenticated workspace
  await expect(page).toHaveURL("http://localhost:3000/auth/login");

  // The "Welcome Back," heading should still be visible, confirming no login occurred
  await expect(heading).toBeVisible();

  // Expect some error/feedback indication in response to the invalid PAT submission
  const errorIndicator = page.getByText(/invalid|error|incorrect|failed|unauthorized/i).first();
  await expect(errorIndicator).toBeVisible({ timeout: 10000 });

  await shot(page, "error-message-visible");
});