/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify system behavior with invalid or expired PAT
 * Ticket: testable#273 · Case: 86063b76-7ec6-4ed7-acd2-800d30ce70cf · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("@case:86063b76-7ec6-4ed7-acd2-800d30ce70cf Verify system behavior with invalid or expired PAT", async ({ page }) => {
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForTimeout(2500);

  await expect(page.getByRole("heading", { name: "Welcome Back," })).toBeVisible();
  await shot(page, "login-page-loaded");

  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");

  await emailInput.click();
  await emailInput.pressSequentially("pat-user@example.com", { delay: 30 });
  await shot(page, "email-entered");

  await passwordInput.click();
  await passwordInput.pressSequentially("expired-pat-token-XXXXX-INVALID", { delay: 30 });
  await shot(page, "invalid-pat-entered");

  await page.getByRole("button", { name: "Authenticate" }).click();
  await page.waitForTimeout(2500);
  await shot(page, "after-submit-invalid-pat");

  // Expected: remain on login page, no dashboard navigation
  await expect(page).toHaveURL("http://localhost:3000/auth/login");
  await expect(page.getByRole("heading", { name: "Welcome Back," })).toBeVisible();
  await expect(emailInput).toBeVisible();
  await expect(passwordInput).toBeVisible();
  await expect(page.getByRole("button", { name: "Authenticate" })).toBeVisible();

  await shot(page, "still-on-login-page");
});