/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify UI Display of Imported Test Cases
 * Ticket: testable#273 · Case: fdbe9a0e-20df-4e29-b9ee-6b9564a7506d · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("testable#273 — Verify UI Display of Imported Test Cases @case:fdbe9a0e-20df-4e29-b9ee-6b9564a7506d", async ({ page }) => {
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForLoadState("domcontentloaded");
  await shot(page, "login-page-loaded");

  await expect(page).toHaveURL("http://localhost:3000/auth/login");
  await expect(page.getByRole("heading", { name: "Welcome Back," })).toBeVisible();

  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");
  const authenticateButton = page.getByRole("button", { name: "Authenticate" });

  await emailInput.click();
  await emailInput.pressSequentially("testuser@example.com", { delay: 30 });
  await shot(page, "filled-email-username");

  await passwordInput.click();
  await passwordInput.pressSequentially("SecurePass123!", { delay: 30 });
  await shot(page, "filled-password");

  await Promise.all([
    page.waitForURL((url) => url.pathname !== "/auth/login", { timeout: 15000 }),
    authenticateButton.click(),
  ]);

  await page.waitForLoadState("domcontentloaded");
  await shot(page, "post-login-landing");

  await expect(page).not.toHaveURL("http://localhost:3000/auth/login");
});