/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify Authentication Error Handling for Invalid PAT
 * Ticket: testable#273 · Case: d874bfb1-c7bd-4344-b1ef-60b1a2a2bd75 · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("testable#273 Verify Authentication Error Handling for Invalid PAT @case:d874bfb1-c7bd-4344-b1ef-60b1a2a2bd75", async ({ page }) => {
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForTimeout(2500);
  await shot(page, "initial-load");

  const heading = page.getByText("Welcome Back,");
  await expect(heading).toBeVisible();

  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");
  const authenticateButton = page.getByRole("button", { name: "Authenticate" });

  await expect(emailInput).toBeVisible();
  await expect(passwordInput).toBeVisible();
  await expect(authenticateButton).toBeVisible();

  await emailInput.click();
  await emailInput.pressSequentially("invalid-pat-user@example.com", { delay: 30 });
  await shot(page, "filled-email");

  await passwordInput.click();
  await passwordInput.pressSequentially("invalid-pat-token-12345", { delay: 30 });
  await shot(page, "filled-password");

  await authenticateButton.click();
  await page.waitForTimeout(2500);
  await shot(page, "after-submit");

  await expect(page).toHaveURL("http://localhost:3000/auth/login");
  await expect(heading).toBeVisible();
  await expect(emailInput).toBeVisible();
  await expect(passwordInput).toBeVisible();
  await expect(authenticateButton).toBeVisible();

  await shot(page, "final-state-login-page");
});