/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify Successful Azure DevOps Provider Configuration
 * Ticket: testable#273 · Case: 12da2a41-3c8a-4e84-8913-5ad93eeb3202 · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("@case:12da2a41-3c8a-4e84-8913-5ad93eeb3202 Verify Successful Azure DevOps Provider Configuration", async ({ page }) => {
  // Step 1: Navigate to root, expect redirect to /auth/login
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForTimeout(2000);
  await shot(page, "initial-load");

  await expect(page).toHaveURL(/\/auth\/login/);
  await expect(page.getByText("Welcome Back,")).toBeVisible();
  await shot(page, "login-page-redirected");

  // Step 2: Fill in email/username
  const emailInput = page.getByPlaceholder("Email or username");
  await emailInput.click();
  await emailInput.pressSequentially("testuser@example.com", { delay: 30 });
  await shot(page, "filled-email");

  // Step 3: Fill in password
  const passwordInput = page.getByPlaceholder("Password");
  await passwordInput.click();
  await passwordInput.pressSequentially("ValidPassword123!", { delay: 30 });
  await shot(page, "filled-password");

  // Step 4: Click Authenticate
  const authenticateButton = page.getByRole("button", { name: "Authenticate" });
  await authenticateButton.click();
  await page.waitForTimeout(3000);
  await shot(page, "after-authenticate");

  // Expected result: navigation away from /auth/login, no error message shown
  await expect(page).not.toHaveURL(/\/auth\/login/);
  await shot(page, "logged-in-state");
});