/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify error handling for expired or invalid PAT
 * Ticket: testable#273 · Case: 883228d3-87b0-43a0-a30e-83de7fc99580 · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("@case:883228d3-87b0-43a0-a30e-83de7fc99580 Verify error handling for expired or invalid PAT", async ({ page }) => {
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForTimeout(2500);

  await shot(page, "initial-login-page");

  await expect(page).toHaveURL("http://localhost:3000/auth/login");
  await expect(page.getByText("Welcome Back,")).toBeVisible();

  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");

  await emailInput.click();
  await emailInput.pressSequentially("expired-pat-user@example.com", { delay: 30 });
  await shot(page, "entered-username");

  await passwordInput.click();
  await passwordInput.pressSequentially("expired_invalid_pat_123456789", { delay: 30 });
  await shot(page, "entered-invalid-pat");

  const authenticateButton = page.getByRole("button", { name: "Authenticate" });
  await authenticateButton.click();

  await page.waitForTimeout(2500);
  await shot(page, "after-authenticate-click");

  // Expected: remain on login page, no successful redirect to authenticated workspace
  await expect(page).toHaveURL("http://localhost:3000/auth/login");

  // Expected: an error message/indicator is displayed near the form
  const errorLocator = page.getByText(/invalid|expired|incorrect|error|failed/i).first();
  await expect(errorLocator).toBeVisible();
  await shot(page, "error-message-visible");

  // Expected: no authenticated session established, login form remains visible
  await expect(page.getByText("Welcome Back,")).toBeVisible();
  await expect(emailInput).toBeVisible();
  await expect(passwordInput).toBeVisible();
  await expect(authenticateButton).toBeVisible();
  await shot(page, "login-form-still-visible");
});