/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify grouping of imported test cases by parent suite in UI
 * Ticket: testable#273 · Case: f9f6aea4-99fd-435c-8227-9ce6a910dbbb · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("testable#273 — Verify grouping of imported test cases by parent suite in UI @case:f9f6aea4-99fd-435c-8227-9ce6a910dbbb", async ({ page }) => {
  test.setTimeout(120000);

  // Step 1: Navigate to the app root, which redirects to /auth/login
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForLoadState("domcontentloaded");
  await shot(page, "login-page-loaded");

  await expect(page.getByRole("heading", { name: "Welcome Back," })).toBeVisible();

  // Step 2: Enter a valid value into the "Email or username" input
  const emailInput = page.getByPlaceholder("Email or username");
  await expect(emailInput).toBeVisible();
  await emailInput.click();
  await emailInput.pressSequentially("testuser@example.com", { delay: 30 });
  await shot(page, "entered-email");

  // Step 3: Enter a valid value into the "Password" input
  const passwordInput = page.getByPlaceholder("Password");
  await expect(passwordInput).toBeVisible();
  await passwordInput.click();
  await passwordInput.pressSequentially("ValidPassword123!", { delay: 30 });
  await shot(page, "entered-password");

  // Step 4: Click the "Authenticate" button to sign in
  const authenticateButton = page.getByRole("button", { name: "Authenticate" });
  await expect(authenticateButton).toBeVisible();
  await authenticateButton.click();

  // Wait for the app to navigate away from the login page after the auth request completes,
  // instead of relying on a fixed timeout which can be too short.
  await page
    .waitForURL((url) => !/\/auth\/login/.test(url.pathname), { timeout: 15000 })
    .catch(() => undefined);
  await shot(page, "after-authenticate-submit");

  // Expected result: redirected away from /auth/login into the authenticated workspace
  await expect(page).not.toHaveURL(/\/auth\/login/, { timeout: 15000 });
  await expect(page.getByRole("heading", { name: "Welcome Back," })).not.toBeVisible();
  await shot(page, "authenticated-workspace");

  // Note: Grouping of imported test cases by parent suite cannot be verified further
  // since no test-case list, suite tree, or grouping UI elements were captured
  // in the current snapshot data for that section of the workspace.
});