/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify deduplication with slight timing delay
 * Ticket: testable#227 · Case: 39357d68-98da-479c-8a8b-a3f9b8883660 · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("@case:39357d68-98da-479c-8a8b-a3f9b8883660 Verify deduplication with slight timing delay", async ({ page }) => {
  // 1. Navigate and confirm redirect to /auth/login
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForTimeout(2500);
  await expect(page).toHaveURL(/\/auth\/login/);
  await shot(page, "login-page-loaded");

  // 2 & 3. Fill in credentials
  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");

  await emailInput.click();
  await emailInput.pressSequentially("testuser@example.com", { delay: 30 });

  await passwordInput.click();
  await passwordInput.pressSequentially("Password123!", { delay: 30 });

  await shot(page, "credentials-filled");

  const authButton = page.getByRole("button", { name: "Authenticate" });
  await expect(authButton).toBeVisible();

  // 4. First submission — establishes the payload/hash
  await authButton.click();
  await shot(page, "first-authenticate-click");

  // 5. Immediately re-click with only a slight delay to simulate rapid double-submit
  await page.waitForTimeout(250);
  await authButton.click().catch(() => undefined);
  await shot(page, "second-authenticate-click-rapid");

  // 6. Observe resulting navigation/state after both submissions resolve
  await page.waitForTimeout(3000);
  await shot(page, "post-submission-settled-state");

  // Expected: single successful authentication/session — user is navigated away from login
  await expect(page).not.toHaveURL(/\/auth\/login/, { timeout: 15000 });

  // Expected: no duplicate error/session/side-effect visible (e.g. no repeated error banners)
  const duplicateErrorLocator = page.getByText(/duplicate|already logged in|invalid credentials/i);
  await expect(duplicateErrorLocator).toHaveCount(0);

  // Expected: the Authenticate/login form is no longer present, confirming a single
  // authenticated end-state (not stuck re-showing the login form for a second attempt)
  await expect(page.getByRole("button", { name: "Authenticate" })).toHaveCount(0);

  await shot(page, "final-authenticated-state");
});