/**
 * @testable-generated — Playwright spec generated by Testable AI.
 * Verify non-deduplication of different payload hashes
 * Ticket: testable#227 · Case: ab02546b-232d-4a52-a42e-085e6932388d · Source: AI_TICKET
 * Manual edits may be overwritten by the next Testable sync.
 */
import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";

const SHOTS = process.env.PW_SHOTS as string;
let n = 0;
async function shot(page: Page, name: string) {
  fs.mkdirSync(SHOTS, { recursive: true });
  n += 1;
  await page.screenshot({ path: `${SHOTS}/${String(n).padStart(2, "0")}-${name}.png` }).catch(() => undefined);
}

test("testable#227 — Verify non-deduplication of different payload hashes @case:ab02546b-232d-4a52-a42e-085e6932388d", async ({ page }) => {
  // 1. Navigate to the app root, which redirects to /auth/login
  await page.goto("http://localhost:3000/", { waitUntil: "commit" });
  await page.waitForLoadState("domcontentloaded");
  await shot(page, "login-page-loaded");

  // Verify login page loaded with expected heading and inputs
  await expect(page.getByRole("heading", { name: "Welcome Back," })).toBeVisible();

  const emailInput = page.getByPlaceholder("Email or username");
  const passwordInput = page.getByPlaceholder("Password");
  const authenticateButton = page.getByRole("button", { name: "Authenticate" });

  await expect(emailInput).toBeVisible();
  await expect(passwordInput).toBeVisible();
  await expect(authenticateButton).toBeVisible();

  // 2. Fill in the email/username field
  await emailInput.click();
  await emailInput.pressSequentially("testuser@example.com", { delay: 30 });
  await shot(page, "filled-email-username");

  // 3. Fill in the password field
  await passwordInput.click();
  await passwordInput.pressSequentially("ValidPassword123!", { delay: 30 });
  await shot(page, "filled-password");

  // 4. Click Authenticate to log in
  await authenticateButton.click();

  // Wait for the SPA to actually navigate away from the login route instead of
  // relying on a fixed timeout (which can be too short/racy in slower runs).
  await page
    .waitForURL((url) => !url.pathname.includes("/auth/login"), { timeout: 15000 })
    .catch(() => undefined);
  await shot(page, "after-authenticate-click");

  // 5. Verify user is navigated away from /auth/login (successful authentication),
  // which establishes the authenticated context needed to exercise
  // payload-hash deduplication behaviour.
  await expect(page).not.toHaveURL(/\/auth\/login/, { timeout: 15000 });
});